version: "3.8"

services:
  web:
    image: "${DHIS2_IMAGE:-dhis2/core-dev:local}"
    ports:
      - 127.0.0.1:8080:8080
    volumes:
      - ./docker/dhis.conf:${DHIS2_HOME:-/DHIS2_home}/dhis.conf
    environment:
      DHIS2_HOME: ${DHIS2_HOME:-/DHIS2_home}
    depends_on:
      db:
        condition: service_healthy

  db:
    image: ghcr.io/baosystems/postgis:12-3.3
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_USER: dhis
      POSTGRES_DB: dhis
      POSTGRES_PASSWORD: &postgres_password dhis
      PGPASSWORD: *postgres_password # needed by psql in healthcheck
    healthcheck:
      test: [ "CMD-SHELL", "psql --no-password --quiet --username $$POSTGRES_USER postgres://127.0.0.1/$$POSTGRES_DB -p 5432 --command \"SELECT 'ok'\" > /dev/null" ]
      start_period: 120s
      interval: 1s
      timeout: 3s
      retries: 5
